title: <p align="center"> Raiyan Hassan </p>
logo: /assets/img/mypic.jpg

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="">LinkedIn</a> |
  <a href="https://github.com/RahaIz15">GitHub</a>
  
  <br>   
  As an Applied and Agentic AI specialist, I bring a wealth of knowledge to cutting-edge projects. My portfolio showcases hands-on work in developing intelligent systems and optimizing real-world challenges. Each project reflects my commitment to innovative solutions and a deep understanding of AI's practical applications. 
  Working in FinTech domain for 6 years.
  <br>
  </p>
theme: jekyll-theme-minimal
